
# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-persistent-volume
spec:
  storageClassName: pod-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi