apiVersion: v1
kind: Service
metadata:
  name: blog-service-with-secrets
spec:
  type: LoadBalancer
  selector:
    app: blog-app-with-secrets
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment-with-secrets
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog-app-with-secrets
  template:
    metadata:
      labels:
        app: blog-app-with-secrets
    spec:
      containers:
      - name: blog-app-with-secrets
        image: us-central1-docker.pkg.dev/fall-week7-2/kontti-repo/assesment-test-master:v5
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: salaisuudet
                key: username
          - name: DATABASE
            valueFrom:
              secretKeyRef:
                name: salaisuudet
                key: databasename
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: salaisuudet
                key: password