apiVersion: v1
kind: Service
metadata:
  name: assesment-app-service
spec:
  selector:
    app: assesment-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assesment-app
spec:
  selector:
    matchLabels:
      app: assesment-app
  replicas: 4
  template:
    metadata:
      labels:
        app: assesment-app
    spec:
      containers:
      - name: assesment-app
        image: us-central1-docker.pkg.dev/fall-week7-2/kontti-repo/assesment-test-master:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80