apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: assesment
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: juukeli
  # täältä löytyi tietokannan kirjautumistiedot plaintextinä, nää olis kannattanut piilottaa